name: "Update YAML and Commit Output"

on:
  workflow_dispatch:

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository that triggered the workflow
      - name: Checkout current repository
        uses: actions/checkout@v3

      # Step 2: Run the composite action to update the YAML
      - name: Run Update YAML Composite Action
        uses: thisis-charan/dockerlibtest3/.github/actions/update-yaml@main
        with:
          file1-repo: "thisis-charan/dockerlibtest1"  # Repository with ci.yml
          file1-path: "ci.yml"                         # Path to ci.yml in dockerlibtest1
          file2-repo: "thisis-charan/dockerlibtest2"     # Repository with cd.yml
          file2-path: "cd.yml"                         # Path to cd.yml in dockerlibtest2
          output-path: "cicd.yml"                       # Output file name to be added to this repo

      # Step 3: Commit and push the updated YAML file back to the repository
      - name: Commit and Push Updated YAML
        working-directory: ${{ github.workspace }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cicd.yml
          git commit -m "Update YAML file via workflow" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
        shell: bash

 