name: "Update YAML from dockerlibtest1 to dockerlibtest2"

on:
  workflow_dispatch:

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Run Update YAML Composite Action
        uses: thisis-charan/dockerlibtest3/.github/actions/update-yaml@main
        with:
          file1-repo: "thisis-charan/dockerlibtest1"  # Repository containing ci.yml
          file1-path: "ci.yml"                         # Path to ci.yml in dockerlibtest1
          file2-repo: "thisis-charan/dockerlibtest2"     # Repository containing cd.yml
          file2-path: "cd.yml"                         # Path to cd.yml in dockerlibtest2
          output-path: "cicd.yml"   # Optional: if you want to override the output path

      - name: Commit and Push Updated YAML
        working-directory: ${{ github.workspace }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cicd.yml
          git commit -m "Update YAML file via workflow" || echo "No changes to commit"
          git push
        shell: bash
